# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  shell: "apache2 -v"
  changed_when: false
  always_run: yes
  register: _apache_version

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"

- include_vars: apache2.2.yml
  when: "apache_version.split('.')[1] == '2'"

- include_vars: apache2.4.yml
  when: "apache_version.split('.')[1] == '4'"

- name: Enable apache2 mod rewrite
  apache2_module: state=present name=rewrite

- name: Configure apache2 include_path for Ice
  template: src=etc-php5-apache2-conf.d/IcePHP.ini.j2 dest=/etc/php5/apache2/conf.d/IcePHP.ini
  notify: restart apache2

- name: Check if IcePHP is not compile in wrong directory
  stat: path="/usr/lib/php5/20090626+lfs/IcePHP.so"
  register: ice_wrong_path

- name: Make symbolic link if IcePHP is in wrong folder
  file: src="/usr/lib/php5/20090626+lfs/IcePHP.so" dest="/usr/lib/php5/20090626/IcePHP.so" state=link
  when: ice_wrong_path.stat.exists

- name: Configure apache2
  template: src="etc-apache2-sites-available/{{ mymumb_apache_default_vhost_filename }}.j2" dest="/etc/apache2/sites-available/{{ mymumb_apache_default_vhost_filename }}"
  notify: restart apache2
