---

- name: Install apache2 if needed
  apt: name="{{ item }}" state=present
  with_items: mymumb_apache2_packages
  when: mymumb_install_apache2

- name: Install requirements
  apt: name="{{ item }}" state=present
  with_items: mymumb_dependencies

- name: Download mymumb archive
  get_url:
      url="{{ mymumb_release_url }}"
      dest="/tmp/mymumb-latest.zip"

- name: Extract mymumb release
  unarchive: src=/tmp/mymumb-latest.zip dest=/tmp copy=no

- name: Remove mymumb archive
  command: rm -f /tmp/mymumb-latest.zip

- name: Remove Previous installation
  command: rm -Rf {{ mymumb_path }}

- name: Moving new installation to destination folder
  command: mv /tmp/MyMumb-Panel-master {{ mymumb_path }}


- name: Fix permissions on mymumb folder
  command: chown -R {{ mymumb_chmod_user }}:{{ mymumb_chmod_group }} {{ mymumb_path }}


